file = open("sample.txt", "w")
file.write("Hello World\n")
file.write("Welcome to Python File Handling\n")
lines = ["Line 0\n", "Line 1\n", "Line 2\n"]
file.writelines(lines)
file.close()
file = open("sample.txt", "r")
print("Using read():")
print(file.read())  
file.seek(2) 
print("Using readline():")
print(file.readline()) 
print(file.readline())  
file.seek(2)
print("Using readlines():")
print(file.readlines())  
file.close()
